version: '3.1'
services:
  testDb:
    image: postgres:12-alpine
    restart: always
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: nesttest
      POSTGRES_PASSWORD: nesttest
